# Generated by Django 4.2.7 on 2023-11-05 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classic_address', models.CharField(max_length=100)),
                ('x_address', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=100)),
                ('seed', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=6, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
