# Generated by Django 4.2.7 on 2023-12-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrpapp', '0004_xrptestwallet_rename_xrpwallet_xrprealwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrprealwallet',
            name='balanceTwo',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=19),
        ),
    ]
