# Generated by Django 4.2.7 on 2023-12-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xrpapp', '0005_xrprealwallet_balancetwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xrprealwallet',
            name='balanceTwo',
        ),
    ]
