# Generated by Django 4.1.5 on 2023-12-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrpapp', '0007_xrprealwallet_user_id_xrptestwallet_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrprealwallet',
            name='user_id',
            field=models.CharField(default='placeholder_user_id', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xrptestwallet',
            name='user_id',
            field=models.CharField(default='placeholder_user_id', max_length=200),
            preserve_default=False,
        ),
    ]
